exp_name: 'zero_shot_exp'
gcp_dir_name: 'gcs://soi-models/VMD-classifier-paper'
classes: ['person', 'vehicle'] 

# dataset name is in this format: dataset_dir/.json
train_datasets: ['MONET/dirtroad_train.json'
                 #'hit-uav/train.json',
                 #'hit-uav/test.json',
                 #'hit-uav/val.json'
                 # 'MONET/data.json'
                 ]

val_datasets: ['MONET/dirtroad_val.json']

test_datasets: ['MONET/dirtroad_test.json']

add_background_label: True
epochs: 30
model: 'resnet18'
devices: [0]