exp_name: 'ronen-classifier'
gcp_dir_name: 'gcs://soi-models/VMD-classifier'
classes: ['person', 'vehicle'] 

# dataset name is in this format: dataset_dir/.json
train_datasets: ['hit-uav/train.json', 
                 'Tel_Yitzhak_23102023_drone_middle_3_T - Trim2/annotations.json',
                 'Tel_Yitzhak_23102023_drone_middle_IRX_0002 - Trim4/annotations.json'
                 ]

val_datasets: ['hit-uav/val.json', 'task_tel_yitzhak_23102023_drone_low_2_t-2023_11_01_15_33_34-coco 1.0/annotations.json']

test_datasets: ['hit-uav/test.json']

add_background_label: True
epochs: 20
model: 'resnet18'
devices: 1